Update for 18.10.0
WeAreFairphone/modem_zip_generator pull request #12
Opened 2018-11-21 12:29 UTC by z3ntu

Fixes #11

2018-11-30 15:12 UTC, stephankusch commented
Works as expected now.

2018-12-31 00:56 UTC, Roboe requested changes
Thank you for reminding me this at Mastodon! I forgot about it, sorry.

Overall it looks good, but I don't like the idea of including a non-versioned binary for the Edify interpreter at all on the repo, :/

The general idea of the Makefile is:
  1. get the Edify interpreter from a OTA release → set ```OTA_*``` variables
  2. get the firmware images from a MANUAL release → set ```FWUPDATE_*``` variables
    - this can also be a OTA release, if it includes every firmware img. GNU Make is a clever system and won't download two identical ZIPs.
  3. pack them into a ready-to-flash ZIP file

I'm aware that latest FP Open doesn't come with an OTA release, so we could just get the Edify interpreter from a previous OTA release. There shouldn't be any issue and doing so it keeps the Makefile more mantainable.

Could you make the changes? If not, I can do it whenever I got a computer nearby, i.e. next year. Happy New Year!

2019-01-01 18:17 UTC, Roboe reviewed
It looks quite better now! I'll accept It once I build & test it in a few days. Thank you, good work! 😊

2019-01-01 18:17 UTC, Roboe commented on Makefile
> +
I'm not sure if this line can be there. Are you sure It doesn't conflict with Make's strict syntax?

2019-01-01 19:27 UTC, z3ntu commented on Makefile
> +
L48 is just declaring a rule(?) called `build` and it has a dependency `FLASHABLEZIP`.

In (now) L50 the `FLASHABLEZIP` rule gets defined.

So afaik both lines have nothing to do with each other (and I seperated it on purpose to show that)

2019-01-02 18:52 UTC, Roboe commented on Makefile
> +
Oh, right, it just looked dangerous in a quick view, but it's an "alias" target (what you call rule). You are right, it looks more clear that way. I'll add another in L116 for the ```release``` target.

2019-01-02 20:08 UTC, Roboe approved these changes
It's installing and working fine in my FP2. Well done, @z3ntu!

2019-01-02 20:10 UTC, merged